from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
import io
import json
from pathlib import Path
import re
from typing import Any

import cv2
import numpy as np
import segno
import zxingcpp


SEAT_REGEX = re.compile(r"^[0-9]{1,2}[A-Z]{1,2}[0-9]{1,2}$")
EXCEL_SCIENTIFIC_SEAT_REGEX = re.compile(r"^([0-9]{1,2})\.0+E\+([0-9]{1,2})$", re.IGNORECASE)


class QRTicketError(ValueError):
    pass


@dataclass(frozen=True)
class QRTicketPayload:
    seat: str
    name: str | None = None


def sanitize_seat_text(text: str) -> str:
    trimmed = text.strip().upper()
    scientific_match = EXCEL_SCIENTIFIC_SEAT_REGEX.fullmatch(trimmed)
    if scientific_match:
        return f"{scientific_match.group(1)}E{scientific_match.group(2)}"

    return re.sub(r"[^A-Z0-9]", "", trimmed)


def normalize_name_text(text: str | None) -> str | None:
    normalized = re.sub(r"\s+", " ", text or "").strip()
    return normalized or None


def validate_ticket_payload(seat: str, name: str | None = None) -> QRTicketPayload:
    normalized_seat = sanitize_seat_text(seat)
    if not SEAT_REGEX.fullmatch(normalized_seat):
        raise QRTicketError("QR ticket seat must look like 6G59, 10AC2, or 10AC13.")

    return QRTicketPayload(seat=normalized_seat, name=normalize_name_text(name))


def serialize_ticket_payload(payload: QRTicketPayload) -> str:
    return payload.seat


def parse_ticket_payload(value: str) -> QRTicketPayload:
    raw_value = value.strip()
    if not raw_value:
        raise QRTicketError("QR payload is empty.")

    # Backward compatibility for QR codes generated by the earlier prototype.
    if raw_value.startswith("{"):
        try:
            decoded = json.loads(raw_value)
        except json.JSONDecodeError as exc:
            raise QRTicketError("QR payload is not valid JSON.") from exc

        if not isinstance(decoded, dict):
            raise QRTicketError("QR payload must be a JSON object.")
        seat = decoded.get("seat")
        name = decoded.get("name")
        if not isinstance(seat, str):
            raise QRTicketError("QR payload must include a string seat field.")
        return validate_ticket_payload(seat, name if isinstance(name, str) else None)

    return validate_ticket_payload(raw_value)


def make_qr_code(payload: QRTicketPayload, *, micro: bool = True, error: str = "M"):
    try:
        return segno.make(serialize_ticket_payload(payload), micro=micro, error=error)
    except Exception as exc:
        raise QRTicketError(f"Unable to generate QR code: {exc}") from exc


def write_qr_svg(
    path: Path,
    payload: QRTicketPayload,
    *,
    micro: bool = True,
    error: str = "M",
    scale: int = 12,
    border: int = 4,
) -> Path:
    if scale < 1:
        raise QRTicketError("scale must be at least 1.")
    if border < 0:
        raise QRTicketError("border must be non-negative.")

    path.parent.mkdir(parents=True, exist_ok=True)
    qr_code = make_qr_code(payload, micro=micro, error=error)
    qr_code.save(str(path), kind="svg", scale=scale, border=border, xmldecl=True)
    return path


def decode_qr_payloads(image: np.ndarray) -> list[dict[str, Any]]:
    decoded_payloads = _decode_with_zxing(image)
    if not decoded_payloads:
        decoded_payloads = _decode_with_opencv(image)
    return decoded_payloads


def _decode_with_zxing(image: np.ndarray) -> list[dict[str, Any]]:
    if image is None:
        return []

    if len(image.shape) == 3:
        decode_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    else:
        decode_image = image

    decoded_payloads = []
    seen_values: set[str] = set()
    for result in zxingcpp.read_barcodes(decode_image):
        value = result.text or ""
        if not value or value in seen_values:
            continue
        seen_values.add(value)
        payload = parse_ticket_payload(value)
        decoded_payloads.append(
            {
                "payload": payload,
                "raw": value,
                "points": _zxing_position_to_box(result.position),
                "format": str(result.format),
            }
        )

    return decoded_payloads


def _decode_with_opencv(image: np.ndarray) -> list[dict[str, Any]]:
    detector = cv2.QRCodeDetector()
    decoded_values: list[str] = []
    points_list: list[Any] = []

    try:
        found, decoded_info, points, _ = detector.detectAndDecodeMulti(image)
    except cv2.error:
        found = False
        decoded_info = ()
        points = None

    if found:
        decoded_values.extend(value for value in decoded_info if value)
        if points is not None:
            points_list = list(points)

    if not decoded_values:
        value, points, _ = detector.detectAndDecode(image)
        if value:
            decoded_values.append(value)
            points_list = [points] if points is not None else []

    decoded_payloads = []
    for index, value in enumerate(decoded_values):
        payload = parse_ticket_payload(value)
        decoded_payloads.append(
            {
                "payload": payload,
                "raw": value,
                "points": _points_to_box(points_list[index] if index < len(points_list) else None),
                "format": "QR Code",
            }
        )

    return decoded_payloads


def _zxing_position_to_box(position: Any) -> list[list[int]]:
    if position is None:
        return []

    points = [position.top_left, position.top_right, position.bottom_right, position.bottom_left]
    return [[int(round(float(point.x))), int(round(float(point.y)))] for point in points]


def _points_to_box(points: Any) -> list[list[int]]:
    if points is None:
        return []

    array = np.asarray(points).reshape(-1, 2)
    return [[int(round(float(x))), int(round(float(y)))] for x, y in array[:4]]


def _iter_csv_reader_payloads(reader: csv.DictReader):
    if "Seat No" not in (reader.fieldnames or []):
        raise QRTicketError("CSV must include Seat No.")

    for row_number, row in enumerate(reader, start=2):
        try:
            yield row_number, validate_ticket_payload(row.get("Seat No", ""), row.get("Name") or row.get("Chinese Name"))
        except QRTicketError as exc:
            raise QRTicketError(f"CSV row {row_number}: {exc}") from exc


def iter_csv_payloads_from_text(csv_text: str):
    reader = csv.DictReader(io.StringIO(csv_text))
    yield from _iter_csv_reader_payloads(reader)


def _iter_csv_payloads(csv_path: Path):
    with csv_path.open("r", encoding="utf-8-sig", newline="") as file_handle:
        reader = csv.DictReader(file_handle)
        yield from _iter_csv_reader_payloads(reader)


def convert_csv_text_to_qr_svgs(
    csv_text: str,
    output_dir: Path,
    *,
    micro: bool = True,
    error: str = "M",
    scale: int = 12,
    border: int = 4,
) -> list[dict[str, str]]:
    output_dir.mkdir(parents=True, exist_ok=True)
    generated_files = []
    for _, payload in iter_csv_payloads_from_text(csv_text):
        path = output_dir / f"{payload.seat}.svg"
        write_qr_svg(path, payload, micro=micro, error=error, scale=scale, border=border)
        generated_files.append({"seat": payload.seat, "filename": path.name, "path": str(path)})
    return generated_files


def generate_one(args: argparse.Namespace) -> int:
    payload = validate_ticket_payload(args.seat, args.name)
    path = write_qr_svg(
        args.output,
        payload,
        micro=not args.regular_qr,
        error=args.error,
        scale=args.scale,
        border=args.border,
    )
    print(path)
    return 0


def generate_batch(args: argparse.Namespace) -> int:
    csv_text = args.csv.read_text(encoding="utf-8-sig")
    generated_files = convert_csv_text_to_qr_svgs(
        csv_text,
        args.output_dir,
        micro=not args.regular_qr,
        error=args.error,
        scale=args.scale,
        border=args.border,
    )
    count = len(generated_files)
    print(f"Generated {count} SVG QR code(s) in {args.output_dir}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate SVG QR codes for OCR Ticket Reader tickets.")
    parser.add_argument("--scale", type=int, default=12, help="SVG module scale. Default: 12.")
    parser.add_argument("--border", type=int, default=4, help="White border in modules. Default: 4.")
    parser.add_argument("--error", choices=["L", "M", "Q", "H"], default="M", help="Error correction level. Default: M.")
    parser.add_argument("--regular-qr", action="store_true", help="Generate a regular QR Code instead of Micro QR.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    generate_parser = subparsers.add_parser("generate", help="Generate one SVG QR code.")
    generate_parser.add_argument("--seat", required=True, help="Seat number, for example 10AC13.")
    generate_parser.add_argument("--name", help="Optional holder name for CSV traceability; not encoded in the QR.")
    generate_parser.add_argument("--output", required=True, type=Path, help="Output SVG path.")
    generate_parser.set_defaults(func=generate_one)

    batch_parser = subparsers.add_parser("batch", help="Generate SVG QR codes from names.csv.")
    batch_parser.add_argument("--csv", required=True, type=Path, help="CSV with a Seat No column.")
    batch_parser.add_argument("--output-dir", required=True, type=Path, help="Folder for generated SVG files.")
    batch_parser.set_defaults(func=generate_batch)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        return args.func(args)
    except QRTicketError as exc:
        parser.error(str(exc))
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
